export const types = {
    CHANGE_TITLE: 'CHANGE_TITLE',
    ADD_TODO: 'ADD_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    SET_FILTER: 'SET_FILTER',
    RESET_FILTER: 'RESET_FILTER'
}