export const types = {
    CHANGE_TITLE: 'CHANGE_TITLE',
    CHANGE_ABOUT_TITLE: 'CHANGE_ABOUT_TITLE',
    WITH_PARAMS: 'WITH_PARAMS',
    FROM_INPUT: 'FROM_INPUT',
    ADD_TASK: 'ADD_TASK',
    DELETE_TASK: 'DELETE_TASK',
    EDIT_TASK: 'EDIT_TASK',
    GET_CATS: 'GET_CATS'
}